import { Metadata } from 'next'
import './globals.css'
import Modal from '@/components/Modal'

// notes
// children is where the page is rendered into in the layout itself

export const metadata: Metadata = {
  title: 'Trello App Clone',
  description: 'Generated by James',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        
        {children}
        
        <Modal />
        </body> 
    </html>
  )
}
